const G_DATA = [
  { 
    id: '367520', 
    n: "Hollow Knight", 
    dev: "Aukak", 
    ported: true,
    tags: ["Metroidvania", "Action", "Indie", "Dark"],
    desc: "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes filled with challenging combat and deep secrets.",
  },
  { 
    id: '268910', 
    n: "Cuphead", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Platformer", "Difficult", "Run and Gun", "Cartoon"],
    desc: "A classic run and gun action game heavily focused on boss battles, inspired by cartoons of the 1930s with traditional hand-drawn cel animation.",
  },
  { 
    id: '2166060', 
    n: "Amanda the Adventurer", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Indie", "Psychological", "Atmospheric"],
    desc: "Join Amanda and her pal Wooly on a series of adventures. But beneath the cheerful exterior of this children's show lies a sinister secret.",
  },
  { 
    id: '1030300', 
    n: "Hollow Knight Silksong", 
    dev: "Aukak, Breadbb", 
    ported: true,
    tags: ["Metroidvania", "Action", "Adventure", "Indie"],
    desc: "Follow the adventures of Hornet, the deadly guardian of Hallownest, who is kidnapped and taken to the mysterious realm of Farlum",
  },
  { 
    id: '3241660', 
    n: "R.E.P.O.", 
    desc: "R.E.P.O. (which stands for Retrieve, Extract, Profit Operation) is an online cooperative survival horror video game",
    dev: "98cornbins, Kaiden's Arcade", 
    ported: true,
  },
  { 
    id: '2835570', 
    n: "Buckshot Roulette", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Indie", "Action", "Shooter", "Strategy"],
    desc: "A Russian roulette themed strategy game where your wits are your only survival tool.",
  },
  { 
    id: '3314790', 
    n: "Clover Pit", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Adventure", "Puzzle", "Indie", "Exploration"],
    desc: "An adventure game filled with mystery and exploration.",
  },
  { 
    id: '1671340', 
    n: "Fears to Fathom Home Alone", 
    dev: "slqntdevss", 
    ported: true,
    tags: ["Horror", "Stealth", "Survival", "Atmospheric"],
    desc: "A terrifying multiplayer horror game centered on the fear of being home alone.",
  },
  { 
    id: '322170', 
    n: "Geometry Dash", 
    dev: "Breadbb, rohanis0000...", 
    ported: true,
    tags: ["Platformer", "Arcade", "Difficult", "Music"],
    desc: "A challenging rhythm-based platformer that tests your reflexes and timing.",
  },
  { 
    id: '433340', 
    n: "Slime Rancher", 
    dev: "Snubby", 
    ported: true,
    tags: ["Adventure", "Farming", "Colorful", "Casual"],
    desc: "Explore a vibrant alien world and manage your own slime ranch. A colorful first-person farming adventure.",
  },
  { 
    id: '3431040', 
    n: "That's Not My Neighbour", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Puzzle", "Stealth", "Indie"],
    desc: "An eerie neighborhood puzzle adventure where you must avoid the suspicious neighbour.",
  },
  { 
    id: '240720', 
    n: "Getting Over It with Bennett Foddy", 
    dev: "slqntdevss, Breadbb", 
    ported: true,
    tags: ["Psychological Horror", "Difficult", "Physics", "Indie"],
    desc: "Getting Over It with Bennett Foddy is a challenging platformer and physics game in which you control a man trapped in a cauldron.",
  },
  { 
    id: '3359320', 
    n: "SchoolBoy Runaway", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Puzzle", "Adventure", "Simulation"],
    desc: "Schoolboy Runaway is a first-person stealth and puzzle game. You play as a student who has been grounded by his parents after getting bad grades.",
  },
  { 
    id: '3146520', 
    n: "WEBFISHING", 
    dev: "Breadbb, Aukak", 
    ported: true,
    tags: ["Fishing", "Casual", "Cute"],
    desc: "WEBFISHING is a popular indie multiplayer casual fishing simulation video game.",
  },
  { 
    id: '1942280', 
    n: "Brotato", 
    dev: "Stinkalistic", 
    ported: true,
    tags: ["Fishing", "Casual", "Cute"],
    desc: "BrotatoBrotato is a roguelite shooter where you control a potato that wields up to 6 weapons at once.",
  },
  { 
    id: '3722330', 
    n: "Shift At Midnight", 
    dev: "slqntdevss", 
    ported: true,
    img: "https://i.ibb.co/F4WvYcJY/library-capsule.jpg",
    tags: ["Horror", "Retro", "3D"],
    desc: "Shift At Midnight is a cooperative horror and investigation video game for up to three players, in which you take on the role of an employee at a convenience store during the night shift.",
  },
  { 
    id: '1150690', 
    n: "Omori", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Psychological", "Adventure", "Indie"],
    desc: "Omori is a psychological horror adventure game that follows a young boy named Omori as he navigates the complexities of his inner world.",
  },
  { 
    id: '1683460', 
    n: "Yandere Simulator", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Romance", "Adventure", ],
    desc: "Yandere Simulator is a stealth action game that follows the story of a high school student",
  },
  { 
    id: '3242750', 
    n: "Level Devil", 
    dev: "Stonedbybread", 
    ported: true,
    tags: ["Hard", "Indie", "Skill", "Troll"],
    desc: "Level Devil is a challenging platformer that tests your skills and reflexes as you navigate through a series of increasingly difficult levels filled with traps and obstacles.",
  },
  { 
    id: '1454400', 
    n: "Cookie Clicker", 
    dev: "bubbls", 
    ported: true,
    tags: ["Tycoon", "Clicker", "Idle", "Casual"],
    desc: "Cookie Clicker is a simple idle game where you click a cookie to earn points and purchase upgrades.",
  },
  { 
    id: '1228610', 
    n: "Karlson", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Parkour", "Action", "Indie", "First-Person"],
    desc: "Karlson is an action video game currently in development (a first-person shooter) created by the independent developer and YouTuber known as Dani.",
  },
  { 
    id: '1292940', 
    n: "Cube Escape Collection", 
    dev: "Cosmos", 
    ported: true,
    tags: ["Puzzle", "Adventure", "Escape Room"],
    desc: "Cube Escape Collection is a collection of escape room games featuring challenging puzzles and immersive environments.",
  },
  { 
    id: '319510', 
    n: "Five Nights at Freddy's", 
    dev: "irv77", 
    img: "https://cdn2.steamgriddb.com/thumb/a8764d790da8da4b839b2f1cc3542f26.png",
    bg: "https://cdn2.steamgriddb.com/hero_thumb/db36d4e03c06b2174e2eb289f98fad37.jpg",
    ported: true,
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's is a survival horror game where you play as a night guard working at a pizzeria with animatronics.",
  },
  { 
    id: '332800', 
    n: "Five Nights at Freddy's 2", 
    img: "https://cdn2.steamgriddb.com/thumb/2da44b3187ef43f30627344ee47d0741.png",
    bg: "https://cdn2.steamgriddb.com/hero_thumb/35fbd1fd947c3f28341c5994845f294d.jpg",
    dev: "irv77", 
    ported: true,
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's 2 is a survival horror game where you play as a night guard working at a pizzeria with animatronics.",
  },
  { 
    id: '354140', 
    n: "Five Nights at Freddy's 3", 
    dev: "irv77", 
    ported: true,
    img: "https://cdn2.steamgriddb.com/thumb/7143811528faaaab3bc6e776e664555c.png",
    bg: "https://cdn2.steamgriddb.com/hero_thumb/814d904278f8e4cecd61e87d7c857204.jpg",
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's 3 (FNaF 3) is a horror and survival video game in which you work as a night security guard at Fazbear's Fright.",
  },
  { 
    id: '388090', 
    n: "Five Nights at Freddy's 4", 
    dev: "irv77", 
    ported: true,
    img: "https://cdn2.steamgriddb.com/thumb/f17dc7f54276b8b4ae0fe9b3c6d41063.png",
    bg: "https://cdn2.steamgriddb.com/hero_thumb/b6862731daebe8849b5913ef4a279fd3.jpg",
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's 4 (FNaF 4) is the fourth game in the original horror series.",
  },
  { 
    id: '506610', 
    n: "Five Nights at Freddy's: Sister Location", 
    dev: "irv77", 
    ported: true,
      img: "https://cdn2.steamgriddb.com/thumb/1361af76cf6cd8fa439b185a18f5f5ca.png",
      bg: "https://cdn2.steamgriddb.com/hero_thumb/ed42b64ab66c48bc3f0a26a65e9d7349.jpg",
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's: Sister Location (2016) is the fifth main installment in the horror series created by Scott Cawthon.",
  },
  { 
    id: '871720', 
    n: "Ultimate Custom Night", 
    dev: "irv77", 
    ported: true,
    img: "https://cdn2.steamgriddb.com/thumb/ff900f735bb7284f7d73957e6980a2a0.png",
    bg: "https://cdn2.steamgriddb.com/hero_thumb/5d39eac2733613a7e51d91ac3f0f2273.jpg",
    tags: ["Horror", "Survival", "Atmospheric"],
    desc: "Five Nights at Freddy's: Ultimate Custom Night (UCN) is a horror and strategy video game in which you face off against a customizable selection of up to 50 animatronics.",
  },
  { 
    id: '413150', 
    n: "Stardew Valley", 
    dev: "Cirsius", 
    ported: true,
    tags: ["Indie", "Farm", "Chill"],
    desc: "Stardew Valley is a popular role-playing and farm-life simulation video game",
  },
  { 
    id: '2527500', 
    n: "MiSide", 
    dev: "genizy", 
    ported: true,
    tags: ["Horror", "Psychological", "Indie"],
    desc: "MiSide is an indie psychological horror video game developed by AIHASTO.",
  },
  { 
    id: '3205080', 
    n: "Bad Parenting 1: Mr. Red Face", 
    dev: "98cornbins", 
    ported: true,
    tags: ["Horror", "Psychological", "Indie"],
    desc: "Bad Parenting is a popular indie psychological horror video game that tells the story of Ron, a boy who suffers from abuse and neglect at home.",
  },
  { 
    id: '9734614', 
    n: "PolyTrack", 
    dev: "Breadbb", 
    ported: true,
    steam: false,
    bg: "https://cdn2.steamgriddb.com/hero_thumb/c9a1812df586d1d151716b30823d8544.jpg",
    img: "https://i.ibb.co/0pLK7v9G/polytrack.png",
    tags: ["Racing", "Cars", "Chill"],
    desc: "PolyTrack is an exciting low-poly racing game heavily inspired by the Trackmania series.",
  },
  { 
    id: '8439152', 
    n: "Ragdoll Archers", 
    dev: "freebuisness", 
    ported: true,
    steam: false,
    bg: "https://cdn2.steamgriddb.com/hero_thumb/3b100796436aea6c360a29aa02c83504.jpg",
    img: "https://cdn2.steamgriddb.com/thumb/70ebe0a59aa6b1fb31aee28f0bfae939.jpg",
    tags: ["Archery", "Physics", "Indie"],
    desc: "Ragdoll Archers is an exciting physics-based archery game where you control a ragdoll character and shoot arrows at targets.",
  },
  { 
    id: '4825193', 
    n: "Long Cat", 
    dev: "Cosmos", 
    ported: true,
    steam: false,
    bg: "https://i.ibb.co/HLS66XH4/longcat-heroe.png",
    img: "https://i.ibb.co/C51xhrvk/longcat.png",
    tags: ["long", "cat", "hard", "skill"],
    desc: "Long Cat is a fun and challenging platformer game where you control a long cat and navigate through various levels.",
  },
  { 
    id: '6394207', 
    n: "Dino Bros", 
    dev: "MichaelMcKenny", 
    ported: true,
    steam: false,
    bg: "https://i.ibb.co/0jjdxxZJ/dinobros-heroe.png",
    img: "https://i.ibb.co/pjZ1FM32/dinobros.png",
    tags: ["skill", "dino", "bros", "hard"],
    desc: "Dino Bros is a fun and challenging platformer game where you control a dinosaur and navigate through various levels.",
  },
  { 
    id: '6986464', 
    n: "Drive Mad", 
    dev: "EvilMonke", 
    ported: true,
    steam: false,
    bg: "https://cdn2.steamgriddb.com/hero_thumb/710c8330cdf354bd19901cb6829ac26d.png",
    img: "https://cdn2.steamgriddb.com/thumb/720a3d2fe9867a586078a3f40847bd57.jpg",
    tags: ["skill", "physics", "racing", "cars"],
    desc: "Drive Mad is an exciting physics-based racing game where you must drive through tracks filled with obstacles and creative stunts.",
  },
  { 
    id: '8482729', 
    n: "Monkey Mart", 
    dev: "EvilMonke", 
    ported: true,
    steam: false,
    bg: "https://i.ibb.co/ymFStbLK/monkey-mart-heroe.png",
    img: "https://i.ibb.co/4nGXgH8T/monkey-mart.png",
    tags: ["Chill", "Monkey", "Mart", "Indie"],
    desc: "Monkey Mart is a popular casual management and simulation game where you control a cute monkey who runs his own supermarket.",
  },
  { 
    id: '5648798', 
    n: "Blacktop Police Chase", 
    dev: "scammerdad", 
    ported: true,
    steam: false,
    bg: "https://i.postimg.cc/QCdwPtQC/blacktop-police-chase-heroe.png",
    img: "https://i.postimg.cc/j23mrbcw/blacktop-police-chase.png",
    tags: ["Blacktop", "Police", "Chase", "Indie"],
    desc: "Blacktop Police Chase is a popular driving video game in which you take on the role of a driver helping a gang of robbers escape from the law.",
  },
];

