const G_DATA = [
  { 
    id: '367520', 
    n: "Hollow Knight", 
    dev: "Aukak", 
    ported: true,
    tags: ["Metroidvania", "Action", "Indie", "Dark"],
    desc: "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes filled with challenging combat and deep secrets.",
  },
  { 
    id: '268910', 
    n: "Cuphead", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Platformer", "Difficult", "Run and Gun", "Cartoon"],
    desc: "A classic run and gun action game heavily focused on boss battles, inspired by cartoons of the 1930s with traditional hand-drawn cel animation.",
  },
  { 
    id: '2166060', 
    n: "Amanda the Adventurer", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Indie", "Psychological", "Atmospheric"],
    desc: "Join Amanda and her pal Wooly on a series of adventures. But beneath the cheerful exterior of this children's show lies a sinister secret.",
  },
  { 
    id: '1030300', 
    n: "Hollow Knight Silksong", 
    dev: "Aukak, Breadbb", 
    ported: true,
    tags: ["Metroidvania", "Action", "Adventure", "Indie"],
    desc: "Follow the adventures of Hornet, the deadly guardian of Hallownest, who is kidnapped and taken to the mysterious realm of Farlum",
  },
  { 
    id: '3241660', 
    n: "R.E.P.O.", 
    dev: "98cornbins, Kaiden's Arcade", 
    ported: true,
  },
  { 
    id: '2835570', 
    n: "Buckshot Roulette", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Indie", "Action", "Shooter", "Strategy"],
    desc: "A Russian roulette themed strategy game where your wits are your only survival tool.",
  },
  { 
    id: '3314790', 
    n: "Clover Pit", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Adventure", "Puzzle", "Indie", "Exploration"],
    desc: "An adventure game filled with mystery and exploration.",
  },
  { 
    id: '1671340', 
    n: "Fears to Fathom Home Alone", 
    dev: "slqntdevss", 
    ported: true,
    tags: ["Horror", "Stealth", "Survival", "Atmospheric"],
    desc: "A terrifying multiplayer horror game centered on the fear of being home alone.",
  },
  { 
    id: '322170', 
    n: "Geometry Dash", 
    dev: "Breadbb, rohanis0000...", 
    ported: true,
    tags: ["Platformer", "Arcade", "Difficult", "Music"],
    desc: "A challenging rhythm-based platformer that tests your reflexes and timing.",
  },
  { 
    id: '433340', 
    n: "Slime Rancher", 
    dev: "Snubby", 
    ported: true,
    tags: ["Adventure", "Farming", "Colorful", "Casual"],
    desc: "Explore a vibrant alien world and manage your own slime ranch. A colorful first-person farming adventure.",
  },
  { 
    id: '3431040', 
    n: "That's Not My Neighbour", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Horror", "Puzzle", "Stealth", "Indie"],
    desc: "An eerie neighborhood puzzle adventure where you must avoid the suspicious neighbour.",
  },
  { 
    id: '240720', 
    n: "Getting Over It with Bennett Foddy", 
    dev: "slqntdevss, Breadbb", 
    ported: true,
    tags: ["Psychological Horror", "Difficult", "Physics", "Indie"],
    desc: "Getting Over It with Bennett Foddy is a challenging platformer and physics game in which you control a man trapped in a cauldron.",
  },
  { 
    id: '3359320', 
    n: "SchoolBoy Runaway", 
    dev: "Breadbb", 
    ported: true,
    tags: ["Puzzle", "Adventure", "Simulation"],
    desc: "Schoolboy Runaway is a first-person stealth and puzzle game. You play as a student who has been grounded by his parents after getting bad grades.",
  },
  { 
    id: '3146520', 
    n: "WEBFISHING", 
    dev: "Breadbb, Aukak", 
    ported: true,
    tags: ["Fishing", "Casual", "Cute"],
    desc: "WEBFISHING is a popular indie multiplayer casual fishing simulation video game.",
  },
  { 
    id: '1942280', 
    n: "Brotato", 
    dev: "Stinkalistic", 
    ported: true,
    tags: ["Fishing", "Casual", "Cute"],
    desc: "BrotatoBrotato is a roguelite shooter where you control a potato that wields up to 6 weapons at once.",
  },
  { 
    id: '3722330', 
    n: "Shift At Midnight", 
    dev: "slqntdevss", 
    ported: true,
    tags: ["Horror", "Retro", "3D"],
    desc: "Shift At Midnight is a cooperative horror and investigation video game for up to three players, in which you take on the role of an employee at a convenience store during the night shift.",
  }
];
