const juegos = [
  { name: "Level Devil", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game1/index.html", img: "assets/game-images/level-devil.webp", tags: ["arcade", "skill", "2players"] },
  { name: "Stick fighter", url: "https://labgstore21.github.io/g2/class-629/", img: "assets/game-images/stick-fighter.webp", tags: ["action", "skill", "2player"] },
  { name: "Suika Game", url: "https://suikagame.io/game/suika-game/", img: "assets/game-images/suika-game.webp", tags: ["puzzle", "skill", "merge"] },
  { name: "Merge Rot", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game37/index.html", img: "assets/game-images/merge-rot.webp", tags: ["merge", "puzzle"] },
  { name: "Stickman Hook", url: "https://ug17.github.io/play/Stickman-HookUB/", img: "assets/game-images/stickman-hook.webp", tags: ["skill", "arcade"] },
  { name: "Monkey Mart", url: "./games/game12.html", img: "assets/game-images/monkey-mart.webp", tags: ["tycoon", "simulation"] },
  { name: "Apple Worm", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game0/index.html", img: "assets/game-images/apple-worm.webp", tags: ["puzzle"] },
  { name: "My perfect hotel", url: "https://1games.io/game/perfect-hotel/", img: "assets/game-images/my-perfect-hotel.webp", tags: ["tycoon", "simulation"] },
  { name: "Bascket random", url: "./games/game5.html", img: "assets/game-images/bascket_random.webp", tags: ["arcade", "2player"] },
  { name: "Boxing random", url: "./games/game24.html", img: "assets/game-images/boxing_random.webp", tags: ["action", "2player"] },
  { name: "Soccer random", url: "https://slope-game.github.io/new3723/soccer-random/", img: "assets/game-images/soccer_random.webp", tags: ["2player", "skill"] },
  { name: "Volley random", url: "https://mountain-game-games.github.io/g/volleyrandom/index.html", img: "assets/game-images/volley-random.webp", tags: ["2player", "skill"] },
  { name: "Crossy Road", url: "https://crossy-road.gitlab.io/file/", img: "assets/game-images/crossy-road.webp", tags: ["arcade", "skill"] },
  { name: "Paper.io 2", url: "https://nb-ga.github.io/games-site/projects/paperio2/index.html", img: "assets/game-images/paper.io_2.webp", tags: ["io", "skill"] },
  { name: "Police Chase", url: "https://trafficrally.io/blacktop-police-chase.embed", img: "assets/game-images/police-chase.webp", tags: ["racing", "action"] },
  { name: "Stack", url: "https://ug17.github.io/play/Stack/", img: "assets/game-images/stack.webp", tags: ["skill", "arcade"] },
  { name: "Eagler craft launcher", url: "https://yee.pages.dev/", img: "assets/game-images/eaglercraft.webp", tags: ["sandbox"] },
  { name: "Minecraft Web Client", url: "./games/game11.html", img: "assets/game-images/minecraft-web.webp", tags: ["sandbox"] },
  { name: "Terraria", url: "https://scratch.mit.edu/projects/322341152/embed", img: "assets/game-images/terraria.webp", tags: ["sandbox", "simulation"] },
  { name: "Flappy Bird", url: "https://nb-ga.github.io/games-site/projects/flappy-bird/index.html", img: "assets/game-images/flappy_bird.webp", tags: ["arcade", "skill"] },
  { name: "2048", url: "https://nb-ga.github.io/games-site/projects/2048/index.html", img: "assets/game-images/2048.webp", tags: ["puzzle"] },
  { name: "Ball Sort", url: "https://games-site.github.io/projects/ball-sort-puzzle/index.html", img: "assets/game-images/ball-sort.webp", tags: ["puzzle"] },
  { name: "Fun Typing IO", url: "https://game.azgame.io/fun-typing-io/", img: "assets/game-images/fun-typing-io.webp", tags: ["skill", "io"] },
  { name: "Breaking the bank", url: "https://rebemanae.github.io/breaking-the-bank/", img: "assets/game-images/breaking-the-bank.webp", tags: ["puzzle", "skill"] },
  { name: "Hero ball adventures", url: "https://slope-game.github.io/heroball-adventures/", img: "assets/game-images/heroball-adventures.webp", tags: ["arcade"] },
  { name: "Tomb of The Mask", url: "https://slope-game.github.io/new5923/tomb/", img: "assets/game-images/tomb-of-the-mask.webp", tags: ["arcade"] },
  { name: "JetPack JoyRide", url: "./games/game7.html", img: "assets/game-images/jetpack-joyride.webp", tags: ["arcade"] },
  { name: "Block Post", url: "https://bitlifeonline.github.io/class19523/blockpost/", img: "assets/game-images/blockpost.webp", tags: ["skill"] },
  { name: "Parkour Jump", url: "https://bitlifeonline.github.io/parkour-jump/", img: "assets/game-images/parkour-jump.webp", tags: ["skill"] },
  { name: "Motox3m", url: "https://nb-ga.github.io/games-site/projects/moto-x3m/index.html", img: "assets/game-images/moto-x3m.webp", tags: ["racing", "skill"] },
  { name: "Motox3m 2", url: "https://nb-ga.github.io/games-site/projects/moto-x3m-2/index.html", img: "assets/game-images/motox3m_2.webp", tags: ["racing", "skill"] },
  { name: "Motox3m Winter", url: "https://games-site.github.io/projects/moto-x3m-winter/index.html", img: "assets/game-images/moto-x3m-4-winter.webp", tags: ["racing", "skill"] },
  { name: "Motox3m Spooky Land", url: "https://games-site.github.io/projects/moto-x3m-spooky-land/index.html", img: "assets/game-images/moto-x3m-spooky-land.webp", tags: ["racing", "skill"] },
  { name: "Motox3m Pool Party", url: "https://games-site.github.io/projects/moto-x3m-pool-party/index.html", img: "assets/game-images/moto-x3m-5-pool-party.webp", tags: ["racing", "skill"] },
  { name: "Longcat", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game2/index.html", img: "assets/game-images/long_cat.webp", tags: ["arcade", "skill"] },
  { name: "Drive Mad", url: "./games/game31.html", img: "assets/game-images/drive-mad.webp", tags: ["racing", "skill"] },
  { name: "Dino Bros", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game8/index.html", img: "assets/game-images/dino-bros.webp", tags: ["arcade"] },
  { name: "Roper", url: "https://hyhygames.com/games/roper-poki-game/", img: "assets/game-images/roper.webp", tags: ["arcade"] },
  { name: "Recoil", url: "./games/game18.html", img: "assets/game-images/recoil.webp", tags: ["arcade", "action"] },
  { name: "Odd bot", url: "https://play.fancade.com/5D01F70D3373F2DD?key=y8&value=default", img: "assets/game-images/odd-bot.webp", tags: ["arcade"] },
  { name: "Gobble", url: "./games/game3.html", img: "assets/game-images/gobble.webp", tags: ["arcade"] },    
  { name: "Stick Man Climb", url: "https://szhong.4399.com/4399swf//upload_swf/ftp37/gamehwq/20211221/15/index.html", img: "assets/game-images/stickman-climb.webp", tags: ["platform", "skill"] },
  { name: "Stickman Climb 2", url: "https://h5.ant.games/game-assets/17266550232074/index.html", img: "assets/game-images/stickman-climb-2.webp", tags: ["skill", "plataform"] },
  { name: "Fnaf 1", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game24/index.html", img: "assets/game-images/fnaf1.webp", tags: ["horror"] },
  { name: "Fnaf 2", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game25/index.html", img: "assets/game-images/fnaf2.webp", tags: ["horror"] },
  { name: "Fnaf 3", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game26/index.html", img: "assets/game-images/fnaf3.webp", tags: ["horror"] },
  { name: "Fnaf 4", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game27/index.html", img: "assets/game-images/fnaf4.webp", tags: ["horror"] },
  { name: "Fnaf Sister Location", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game28/index.html", img: "assets/game-images/fnaf5.webp", tags: ["horror"] },
  { name: "Fnaf Pizzeria Simulator", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game29/index.html", img: "assets/game-images/fnafps.webp", tags: ["horror"] },
  { name: "Fnaf World", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game30/index.html", img: "assets/game-images/fnafworld.webp", tags: ["horror"] },
  { name: "Fnaf Ultimate Custom Night", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game31/index.html", img: "assets/game-images/fnafucn.webp", tags: ["horror"] },
  { name: "Subway Surfers", url: "https://ug17.github.io/play/Subway-Surfers/", img: "assets/game-images/subway-surfers.webp", tags: ["arcade", "skill"] },
  { name: "Subway Surfers winter holiday", url: "https://ubg77.github.io/updatefaqs/subway-surfers-winter-holiday/", img: "assets/game-images/subway-surfers-winter-holiday.webp", tags: ["arcade", "skill"] },
  { name: "Subway Surfers New York", url: "https://ubg77.github.io/updatefaqs/subway-surfers-nyc/", img: "assets/game-images/subway-surfers-nyc.webp", tags: ["arcade", "skill"] },
  { name: "Subway Surfers Bali", url: "https://ubg77.github.io/updatefaqs/subway-surfers-bali/", img: "assets/game-images/subway-surfers-bali.webp", tags: ["arcade", "skill"] },
  { name: "Temple Run", url: "https://templerun.org/wp-content/uploads/games/html5/T/Temple%20Game%20Jungle/index.html", img: "assets/game-images/temple-run.webp", tags: ["arcade", "skill"] },
  { name: "Temple Run 2 Jungle Fall", url: "https://rebemanae.github.io/temple-run-2-jungle-fall/", img: "assets/game-images/temple-run-2-jungle-fall.webp", tags: ["arcade", "skill"] },
  { name: "Temple Run 2 Frozen Shadows", url: "https://rebemanae.github.io/temple-run-2-jungle-fall/", img: "assets/game-images/temple-run-2-frozen-shadows.webp", tags: ["arcade", "skill"] },
  { name: "Temple Run 2 Holi Festival", url: "https://rebemanae.github.io/temple-run-2-holi-festival/", img: "assets/game-images/temple-run-2-holi-festival.webp", tags: ["arcade", "skill"] },
  { name: "Fireboy & Watergirl 1", url: "https://games-site.github.io/projects/fireboy-and-watergirl-1/index.html", img: "assets/game-images/fireboy&watergirl_1.webp", tags: ["2player", "plataform"] },
  { name: "Fireboy & Watergirl 2", url: "https://games-site.github.io/projects/fireboy-and-watergirl-2/index.html", img: "assets/game-images/fireboy&watergirl_2.webp", tags: ["2player", "plataform"] },
  { name: "Fireboy & Watergirl 3", url: "https://games-site.github.io/projects/fireboy-and-watergirl-3/index.html", img: "assets/game-images/fireboy&watergirl_3.webp", tags: ["2player", "plataform"] },
  { name: "Fireboy & Watergirl 4", url: "https://games-site.github.io/projects/fireboy-and-watergirl-4/index.html", img: "assets/game-images/fireboy&watergirl_4.webp", tags: ["2player", "plataform"] },
  { name: "Fireboy & Watergirl 5", url: "https://games-site.github.io/projects/fireboy-and-watergirl-5/index.html", img: "assets/game-images/fireboy&watergirl_5.webp", tags: ["2player", "plataform"] },
  { name: "Fireboy & Watergirl 6", url: "https://games-site.github.io/projects/fireboy-and-watergirl-6/index.html", img: "assets/game-images/fireboy&watergirl_6.webp", tags: ["2player", "plataform"] },
  { name: "Bad Ice cream", url: "https://bitlifeonline.github.io/bad-ice-cream/", img: "assets/game-images/bad-ice-cream.webp", tags: ["arcade", "2player"] },
  { name: "Bad Ice cream 2", url: "https://onegamez.github.io/bad-ice-cream-2/", img: "assets/game-images/bad-ice-cream-2.webp", tags: ["arcade", "2player"] },
  { name: "Bad Ice cream 3", url: "https://onegamez.github.io/bad-ice-cream-3/", img: "assets/game-images/bad-ice-cream-3.webp", tags: ["arcade", "2player"] },
  { name: "Swingo", url: "https://bitlifeonline.github.io/class12523/swingo/", img: "assets/game-images/swingo.webp", tags: ["arcade", "skill"] },
  { name: "Blumgi ball", url: "https://bitlifeonline.github.io/class12523/blumgi-ball/", img: "assets/game-images/blumgi-ball.webp", tags: ["arcade", "skill"] },
  { name: "Blumgi castle", url: "https://bitlifeonline.github.io/class12523/blumgi-castle/", img: "assets/game-images/blumgi-castle.webp", tags: ["arcade", "skill", "2players"] },
  { name: "Blumgi slime", url: "https://bitlifeonline.github.io/class12523/blumgi-slime/", img: "assets/game-images/blumgi-slime.webp", tags: ["arcade", "skill", "2players"] },
  { name: "Friday Night Funkin", url: "https://fnf.kdata1.com/2025/fnf/7500/", img: "assets/game-images/fnf.webp", tags: ["music", "skill"] },
  { name: "Power Pamplona", url: "https://www.friv.com/z/games/powerpamplona/game.html", img: "assets/game-images/power-pamplona.webp", tags: ["skill", "arcade"] },
  { name: "Boxing Stars", url: "https://www.friv.com/z/games/boxingstars/game.html", img: "assets/game-images/boxing-stars.webp", tags: ["action", "skill"] },
  { name: "Steal a Brainrot", url: "./games/game20.html", img: "assets/game-images/steal-a-brainrot.webp", tags: ["puzzle", "tycoon"] },
  { name: "Plants vs Brainrots", url: "https://st.8games.net/7/8g/igra-brejnroty-protiv-rastenij/", img: "assets/game-images/plants-vs-brainrots.webp", tags: ["puzzle", "tycoon"] },
  { name: "Geometry Dash", url: "https://geometry-dash-lite.1games.io/", img: "assets/game-images/geometry-dash.webp", tags: ["skill", "arcade"] },
  { name: "Geometry Vibes", url: "https://files.twoplayergames.org/files/games/g1/geometry-vibes-v11/index.html", img: "assets/game-images/geometry-vibes.webp", tags: ["skill", "arcade", "2player"] },
  { name: "Harvest Simulator", url: "https://g.igroutka.ru/games/1213/jtFMmdAVoke2w6qL/d8d9f2cc-186e-4695-adce-1ef984e47d59/index.html", img: "assets/game-images/harvest-simulator.webp", tags: ["simulation", "tycoon"] },
  { name: "That's not my neighbor", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game18/index.html", img: "assets/game-images/thats-not-my-neighbor.webp", tags: ["puzzle"] },
  { name: "Raft", url: "./games/game15.html", img: "assets/game-images/raft.webp", tags: ["simulation"] },
  { name: "Hollow Knight", url: "https://2games.io/embed/hollow-knight", img: "assets/game-images/hollow-knight.webp", tags: ["platform"] },
  { name: "Buckshot Roulette", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game19/index.html", img: "assets/game-images/buckshot-roulette.webp", tags: ["platform"] },
  { name: "Cuphead", url: "./games/game40.html", img: "assets/game-images/cuphead.webp", tags: ["platform", "skill", "action"] },
  { name: "R.E.P.O", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game17/index.html", img: "assets/game-images/repo.webp", tags: ["horror", "action"] },
  { name: "Slime Rancher", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game16/index.html", img: "assets/game-images/slime-rancher.webp", tags: ["action"] },
  { name: "Amanda the adventurer", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game21/index.html", img: "assets/game-images/amanda-the-adventurer.webp", tags: ["horror"] },
  { name: "Omori", url: "./games/game38.html", img: "assets/game-images/omori.webp", tags: ["horror"] },
  { name: "Bendi and the ink machine", url: "./games/game24.html", img: "assets/game-images/bendy-and-the-ink-machine.webp", tags: ["horror"] },
  { name: "Bad Parenting 1", url: "./games/game1.html", img: "assets/game-images/bad-parenting.webp", tags: ["horror"] },
  { name: "Fears to fathom home alone", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game22/index.html", img: "assets/game-images/ftp-home-alone.webp", tags: ["horror"] },
  { name: "Rocket soccer derby", url: "https://rocket-soccer-derby.github.io/file/", img: "assets/game-images/rocket-soccer-derby.webp", tags: ["racing"] },
  { name: "Getting over it", url: "./games/game2.html", img: "assets/game-images/getting-over-it.webp", tags: ["skill"] },
  { name: "Head Soccer 2024", url: "https://1games.io/game/head-soccer-2024/", img: "assets/game-images/head-soccer-2024.webp", tags: ["2player", "skill"] },
  { name: "Rubik", url: "https://rubikscu.be/", img: "assets/game-images/rubik.webp", tags: ["puzzle"] },
  { name: "Chill guy clicker", url: "https://game.azgame.io/chill-guy-clicker/", img: "assets/game-images/chill-guy-clicker.webp", tags: ["clicker"] },
  { name: "Cookie Clicker", url: "https://webglmath.github.io/cookie-clicker/", img: "assets/game-images/cookie-clicker.webp", tags: ["clicker"] },
  { name: "Sprunki Clicker", url: "https://game.azgame.io/sprunki-clicker/", img: "assets/game-images/sprunki-clicker.webp", tags: ["clicker"] },
  { name: "Bottle Jump", url: "https://1games.io/game/bottle-jump/", img: "assets/game-images/bottle-jump.webp", tags: ["skill", "arcade"] },
  { name: "Brain Test 1 Tricky Puzzles", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game35/index.html", img: "assets/game-images/brain-test.webp", tags: ["puzzle"] },
  { name: "Brain Test 2 Tricky Stories", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game11/index.html", img: "assets/game-images/brain-test-2-tricky-stories.webp", tags: ["puzzle"] },
  { name: "Brain Test 3 Tricky Quests", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game36/index.html", img: "assets/game-images/brain-test-3.webp", tags: ["puzzle"] },
  { name: "Brain Test 4 Tricky Friends", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game34/index.html", img: "assets/game-images/brain-test-4-tricky-friends.webp", tags: ["puzzle"] },
  { name: "Cut the Rope", url: "https://games-site.github.io/projects/ctr-time-travel/index.html", img: "assets/game-images/cut-the-rope.webp", tags: ["puzzle"] },
  { name: "Papery Planes", url: "./games/game13.html", img: "assets/game-images/papery-planes.webp", tags: ["skill", "arcade"] },
  { name: "Sprunki", url: "https://azgames.io/game/sprunki/", img: "assets/game-images/sprunki.webp", tags: ["arcade"] },
  { name: "Jetski race", url: "https://1games.io/game/jetski-race/", img: "assets/game-images/jetski-race.webp", tags: ["racing", "skill"] },
  { name: "Deer adventure", url: "https://game.azgame.io/deer-adventure/", img: "assets/game-images/deer-adventure.webp", tags: ["arcade", "skill"] },
  { name: "Dude Theft Auto", url: "https://1games.io/game/dude-theft-auto/", img: "assets/game-images/dude-theft-auto.webp", tags: ["action", "skill"] },
  { name: "Billiards Master", url: "https://game.azgame.io/billiards-master/", img: "assets/game-images/billiards-master.webp", tags: ["skill"] },
  { name: "Block Blast 3D", url: "https://game.azgame.io/block-blast-3d/", img: "assets/game-images/block-blast-3d.webp", tags: ["arcade", "skill"] },
  { name: "Snow Road 3D", url: "https://1games.io/game/snow-road-3d/", img: "assets/game-images/snow-road-3d.webp", tags: ["racing", "skill"] },
  { name: "Bike Xtreme", url: "https://azgames.io/bike-xtreme.embed", img: "assets/game-images/bike-xtreme.webp", tags: ["racing", "skill"] },
  { name: "Stickman Racing", url: "https://azgames.io/stickman-racing.embed", img: "assets/game-images/stickman-racing.webp", tags: ["racing", "skill"] },
  { name: "Plants vs Zombies", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game13/index.html", img: "assets/game-images/plants-vs-zombies.webp", tags: ["skill", "arcade"] },
  { name: "Uno Online", url: "https://rawcdn.githack.com/nimogamesdev/ng-source/main/game10/index.html", img: "assets/game-images/uno-online.webp", tags: ["skill"] },
  { name: "Stickman prison escape", url: "https://abinbins.github.io/a7/escaping-the-prison/", img: "assets/game-images/stickman-prison-escape.webp", tags: ["action", "skill"] },
  { name: "Murder", url: "https://h5.ant.games/game-assets/17477130192978/index.html", img: "assets/game-images/murder.webp", tags: ["action", "skill"] },
  { name: "Granny", url: "./games/game39.html", img: "assets/game-images/granny.webp", tags: ["horror"] },
  { name: "Plonky", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game14/index.html", img: "assets/game-images/plonky.webp", tags: ["arcade", "skill"] },
  { name: "Drift.io", url: "https://drift.io/", img: "assets/game-images/drift.io.webp", tags: ["racing", "io"] },
  { name: "Traffic Escape", url: "https://fly.silvergames.com/m/traffic-escape/", img: "assets/game-images/traffic-escape.webp", tags: ["racing", "skill"] },
  { name: "Last chess standing", url: "https://playgroundfree.github.io/last-chess-standing/", img: "assets/game-images/last-chess-standing.webp", tags: ["skill"] },
  { name: "Blood Money!", url: "https://bloodmoney.1games.io/", img: "assets/game-images/blood-money.webp", tags: ["action", "skill"] },
  { name: "Blood Money! 2", url: "https://1games.io/game/bloodmoney-2/", img: "assets/game-images/blood-money-2.webp", tags: ["action", "skill"] },
  { name: "Scary teacher 3D", url: "https://g.igroutka.ru/games/1087/NgleEW1zP8YRpXGI/9d2ca9df-7f2c-4685-8907-e330be4ef190/index.html", img: "assets/game-images/scary-teacher-3d.webp", tags: ["horror"] },
  { name: "SchoolBoy Runaway", url: "./games/game19.html", img: "assets/game-images/school-boy-runaway.webp", tags: ["action", "skill"] },
  { name: "Escape Road City 2", url: "https://1games.io/game/escape-road-city-2/", img: "assets/game-images/escape-road-city-2.webp", tags: ["racing", "skill"] },
  { name: "Ragdoll Archers", url: "https://bitlifeonline.github.io/ragdoll-archers/", img: "assets/game-images/ragdoll-archers.webp", tags: ["skill", "arcade"] },
  { name: "Swipe Ball", url: "https://swipe-ball.1games.io/", img: "assets/game-images/swipe-ball.webp", tags: ["skill", "arcade"] },
  { name: "Flick Goal", url: "https://playgroundfree.github.io/flick-goal/", img: "assets/game-images/flick-goal.webp", tags: ["skill", "arcade"] },
  { name: "Fury Chase 2", url: "https://1games.io/game/fury-chase-2/", img: "assets/game-images/fury-chase-2.webp", tags: ["racing", "skill"] },
  { name: "Golf Hit", url: "https://golf-hit.1games.io/", img: "assets/game-images/golf-hit.webp", tags: ["skill", "arcade"] },
  { name: "Dunk Dash", url: "https://1games.io/game/dunk-dash/", img: "assets/game-images/dunk-dash.webp", tags: ["skill", "arcade"] },
  { name: "Icy Dash", url: "https://1games.io/game/icy-dash/", img: "assets/game-images/icy-dash.webp", tags: ["skill", "arcade"] },
  { name: "Cat and Granny", url: "https://cdn.unblocked-games-free.com/games/4494/KQMUcZ73Nuneoj/390441/saesmjjdi8hyt0nhseqatqa5ku1gadbk/index.html", img: "assets/game-images/cat-and-granny.webp", tags: ["skill"] },
  { name: "Drive Beyond Horizons", url: "https://epicfreegames78.github.io/drive-beyond-horizons/", img: "assets/game-images/drive-beyond-horizons.webp", tags: ["racing", "skill"] },
  { name: "KoGaMa", url: "https://www.kogama.com/games/lagged/9231110/", img: "assets/game-images/kogama.webp", tags: ["sandbox"] },
  { name: "Fruit Ninja", url: "./games/game37.html", img: "assets/game-images/fruit-ninja.webp", tags: ["skill", "arcade"] },
  { name: "Kick the buddy", url: "https://st.8games.net/dasha1/igry-novye/igra-kik-ze-badi/", img: "assets/game-images/kick-the-buddy.webp", tags: ["skill", "action"] },
  { name: "Raft Life", url: "https://freegames78.github.io/raft-life/", img: "assets/game-images/raft-life.webp", tags: ["sandbox", "skill"] },
  { name: "Stickman crazy box", url: "https://bitlifeonline.github.io/stickman-crazy-box/", img: "assets/game-images/stickman-crazy-box.webp", tags: ["skill", "action"] },
  { name: "Ping Pong Go!", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game5/index.html", img: "assets/game-images/ping-pong-go.webp", tags: ["skill"] },
  { name: "Super Mario Bros", url: "https://frivez.com/games/super-mario-bros/index.html", img: "assets/game-images/super-mario-bros.webp", tags: ["platform", "arcade", "action"] },
  { name: "Survival Race", url: "https://st.8games.net/14/igra-bitva-superkarov-3d/", img: "assets/game-images/survival-race.webp", tags: ["racing", "action"] },
  { name: "Traffic rally", url: "https://1games.io/game/traffic-rally/", img: "assets/game-images/traffic-rally.webp", tags: ["racing", "simulation", "skill"] },
  { name: "Brain lines", url: "https://1games.io/game/brain-lines/", img: "assets/game-images/brain-lines.webp", tags: ["puzzle", "skill"] },
  { name: "Poor Rabit", url: "https://newgamesdaily.github.io/poor-bunny/", img: "assets/game-images/poor-rabbit.webp", tags: ["arcade", "skill", "platform"] },
  { name: "Basketball Stars", url: "https://basketball-stars.io/1.embed", img: "assets/game-images/basketball-stars.webp", tags: ["2players", "skill"] },
  { name: "Bounce Up", url: "https://bounce-up.1games.io/", img: "assets/game-images/bounce-up.webp", tags: ["arcade", "puzzle", "skill"] },
  { name: "Stickman Empires", url: "https://stickman-empires.1games.io/", img: "assets/game-images/stickman-empires.webp", tags: ["skill", "action"] },
  { name: "Jump Up", url: "https://1games.io/game/jump-up/", img: "assets/game-images/jump-up.webp", tags: ["arcade", "jump", "platform", "skill"] },
  { name: "Merge Arena", url: "https://bitlifeonline.github.io/merge-arena/", img: "assets/game-images/merge-arena.webp", tags: ["puzzle", "merge", "action"] },
  { name: "Penalty Shootout Multi League", url: "https://bitlifeonline.github.io/penalty-shootout-multi-league/", img: "assets/game-images/penalty-shootout-multi-league.webp", tags: ["skill"] },
  { name: "Gobattle", url: "https://bitlifeonline.github.io/gobattle/", img: "assets/game-images/gobattle.webp", tags: ["puzzle", "action", "2players"] },
  { name: "Cubes 2048.io", url: "https://bitlifeonline.github.io/cubes-2048-io/", img: "assets/game-images/cubes-2048.io.webp", tags: ["arcade", "skill"] },
  { name: "Obby parkour ultimate", url: "https://bitlifeonline.github.io/obby-parkour-ultimate/", img: "assets/game-images/obby-parkour-ultimate.webp", tags: ["platform", "skill"] },
  { name: "Stickmerge", url: "https://webglmath.github.io/stickmerge/", img: "assets/game-images/stickmerge.webp", tags: ["action", "skill", "merge"] },
  { name: "Brawl Stars", url: "https://web.cloudmoonapp.com/es/game/com.supercell.brawlstars/?from=list", img: "assets/game-images/brawl-stars.webp", tags: ["action", "skill"] },
  { name: "Clash Royale", url: "https://web.cloudmoonapp.com/es/game/com.supercell.clashroyale/", img: "assets/game-images/clash-royale.webp", tags: ["action", "skill"] },
  { name: "Clash of Clans", url: "https://web.cloudmoonapp.com/es/game/com.supercell.clashofclans/?from=list", img: "assets/game-images/clash-of-clans.webp", tags: ["action", "skill"] },
  { name: "Pacman", url: "https://www.onlinegames.io/games/2024/more/tapman/index.html", img: "assets/game-images/pacman.webp", tags: ["arcade"] },
  { name: "Rumble rush", url: "https://rumblerush.io", img: "assets/game-images/rumble-rush.webp", tags: ["racing"] },
  { name: "Uphill rush 3", url: "https://files.silvergames.com/flash/ruffle/player.php?id=886", img: "assets/game-images/uphill-rush.webp", tags: ["racing"] },
  { name: "Uphill rush 6", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game7/index.html", img: "assets/game-images/uphill-rush-6.webp", tags: ["racing"] },
  { name: "Happy Wheels", url: "https://flash-games.io/happy-wheels.embed", img: "assets/game-images/happy-wheels.webp", tags: ["racing"] },
  { name: "Kindergarten", url: "./games/game8.html", img: "assets/game-images/kindergarten.webp", tags: ["horror"] },
  { name: "Kindergarten 2", url: "./games/game9.html", img: "assets/game-images/kindergarten-2.webp", tags: ["horror"] },
  { name: "Kindergarten 3", url: "./games/game10.html", img: "assets/game-images/kindergarten-3.webp", tags: ["horror"] },
  { name: "Super smash flash 2", url: "https://flash-games.io/super-smash-flash-2.embed", img: "assets/game-images/super-smash-flash-2.webp", tags: ["action"] },
  { name: "Gun runner", url: "./games/game4.html", img: "assets/game-images/gun-runner.webp", tags: ["action"] },
  { name: "Candy Crush", url: "./games/game27.html", img: "assets/game-images/candy-crush.webp", tags: ["puzzle"] },
  { name: "Crazy Cars", url: "./games/game28.html", img: "assets/game-images/crazy-cars.webp", tags: ["racing", "2players"] },
  { name: "Build now.gg", url: "./games/game26.html", img: "assets/game-images/buildnow.gg.webp", tags: ["action"] },
  { name: "Web Fishing", url: "./games/game22.html", img: "assets/game-images/webfishing.webp", tags: ["tycoon"] },
  { name: "Re Run", url: "./games/game17.html", img: "assets/game-images/re-run.webp", tags: ["action"] },
  { name: "Jelly restaurant", url: "./games/game6.html", img: "assets/game-images/jelly-restaurant.webp", tags: ["tycoon"] },
  { name: "Dadish 3D", url: "./games/game30.html", img: "assets/game-images/dadish-3d.webp", tags: ["arcade"] },
  { name: "Rainbow obby", url: "./games/game16.html", img: "assets/game-images/rainbow-obby.webp", tags: ["arcade, skill"] },
  { name: "Beach boxing simulator", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game9/index.html", img: "assets/game-images/beach-boxing.webp", tags: ["tycoon"] },
  { name: "World Guessr", url: "https://www.worldguessr.com/", img: "assets/game-images/world-guessr.webp", tags: ["puzzle"] },
  { name: "Wordle", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game12/index.html", img: "assets/game-images/wordle.webp", tags: ["puzzle"] },
  {name: "Trivia crack", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game6/index.html", img: "assets/game-images/trivia-crack.webp", tags: ["puzzle"] },
  {name: "Master chess", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game3/index.html", img: "assets/game-images/master-chess.webp", tags: ["puzzle", "skill"] },
  {name: "Golf Party", url: "https://raw.githack.com/nimogamesdev/ng-source/main/game15/index.html", img: "assets/game-images/golf-party.webp", tags: ["racing", "skill"] },
  {name: "Sudoku", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game32/index.html", img: "assets/game-images/sudoku.webp", tags: ["puzzle", "skill"] },
  {name: "Sushi Party", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game33/index.html", img: "assets/game-images/sushi-party.webp", tags: ["racing", "2player"] },
  {name: "Soundboard", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/soundboard/index.html", img: "assets/game-images/soundboard.webp", tags: ["racing", "2player"] },
  {name: "Cube Escape Collections", url: "https://raw.githack.com/nimogamesdev/ng-source-more/main/game38/index.html", img: "assets/game-images/cube-escape.webp", tags: ["puzzle", "skill"] },
];
